#!/bin/bash
##
# Enigma : Online Sales Management. (http://www.enigmagen.org)
# Licensed under The MIT License
# Redistributions of files must retain the above copyright notice.
##

SCRIPT_PATH="${BASH_SOURCE[0]}";
if([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

APP=`dirname $SCRIPT_PATH`
LIB=`dirname $APP`/cakephp/cake/console/

exec php -q ${LIB}cake.php -working "${APP}" "$@"

exit;